 
import Index from '@/modules/Movies/Index'
import Head from 'next/head' 
import { useEffect, useState } from 'react'

 

export default function Home() {
  const [genres, setGenres] = useState([])

  useEffect(() => {

  }, [])
  return (
    <>
      <Head>
        <title>Topset Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-slate-50" id="main">
        <div className='p-8 max-w-screen-xl 2xl:max-w-screen-2xl w-full m-auto '>

        <Index />
        </div>
      </main>
    </>
  )
}
